//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiario_beneficio
    {
        public int id_benef_beneficio { get; set; }
        public int id_beneficiario { get; set; }
        public int id_beneficio { get; set; }
        public System.DateTime fechadesde { get; set; }
    }
}
