//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiario
    {
        public int id_beneficiario { get; set; }
        public int id_barrio { get; set; }
        public int id_grupo { get; set; }
        public string nombre { get; set; }
        public string documento { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    }
}
