//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcion
    {
        public int id_funcion { get; set; }
        public string id_menu { get; set; }
        public string nombre_funcion { get; set; }
        public string nombre_menu { get; set; }
    }
}
