//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemcompra
    {
        public int id_item_compra { get; set; }
        public int id_compra { get; set; }
        public int id_articulo { get; set; }
        public float cantidad { get; set; }
        public float precio_unitario { get; set; }
    }
}
