//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saluddbEntities : DbContext
    {
        public saluddbEntities()
            : base("name=saluddbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<articulo> articuloes { get; set; }
        public DbSet<beneficiario> beneficiarios { get; set; }
        public DbSet<funcion> funcions { get; set; }
        public DbSet<itemcompra> itemcompras { get; set; }
        public DbSet<itementrega> itementregas { get; set; }
        public DbSet<ordenentrega> ordenentregas { get; set; }
        public DbSet<permiso> permisoes { get; set; }
        public DbSet<proveedor> proveedors { get; set; }
        public DbSet<tipoarticulo> tipoarticuloes { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<ordenestado> ordenestadoes { get; set; }
        public DbSet<barrio> barrios { get; set; }
    }
}
