//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenentrega
    {
        public long id_orden { get; set; }
        public int id_beneficiario { get; set; }
        public int id_usuario { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_usu_autoriza { get; set; }
        public Nullable<int> id_usu_entrega { get; set; }
    }
}
