//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processar.ProyectoAyudar.DatosLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenestado
    {
        public int id_ordenestado { get; set; }
        public int id_usuario { get; set; }
        public int id_orden { get; set; }
        public long estado { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
